- block:

    - name: allow local user access
      become: yes
      lineinfile:
        state: present
        dest: /etc/postgresql/9.4/main/pg_hba.conf
        line: "{{ item }}"
        insertafter: ^local\s+all\s+postgres\s+peer$
      with_items:
        - local all {{ db_user }} trust
        - host all {{ db_user }} localhost trust

    - name: restart PostgreSQL
      become: yes
      service: name=postgresql state=restarted

  when: ansible_distribution == "Ubuntu"
