- block:

    - name: install Nginx (Arch)
      pacman: name={{ item }} state=latest
      with_items:
        - nginx
      become: yes

    - name: install nginx template
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: enable Nginx (Arch)
      service: name=nginx enabled=yes state=started
      become: yes

  when: ansible_distribution == "Archlinux"
