- block:

    - name: install Nginx (Arch)
      pacman: name={{ item }} state=latest
      with_items:
        - nginx
      become: yes

    - name: install nginx template
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: auto-restart on crash
      lineinfile:
        state: present
        dest: /usr/lib/systemd/system/nginx.service
        line: Restart=always
        insertafter: \[Service\]

    - name: email on crash
      lineinfile:
        state: present
        dest: /usr/lib/systemd/system/nginx.service
        line: OnFailure=crash-mail@%n.service
        insertafter: \[Unit\]

    - name: enable Nginx (Arch)
      service: name=nginx enabled=yes state=reloaded
      become: yes

  when: ansible_distribution == "Archlinux"
