---

- block:

  - name: install virtualenv (Ubuntu 14)
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python-virtualenv
    when: ansible_lsb.major_release|int <= 14

  - name: install virtualenv (Ubuntu 15+)
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python3-venv
    when: ansible_lsb.major_release|int >= 15

  when: ansible_distribution == "Ubuntu"


- block:

    - name: create virtual environment and install Python requirements
      pip:
        executable: pip3
        virtualenv_command: pyvenv
        virtualenv: "{{ venv_dir }}"
        requirements: "{{ pip_requirements_file }}"
      when: ansible_distribution != "Ubuntu" or ansible_lsb.major_release|int >= 15
      environment:
        CPATH: /usr/include/libxml2

    - name: install Python requirements (Ubuntu 14)
      pip:
        executable: pip3
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python3
        requirements: "{{ pip_requirements_file }}"
      when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int <= 14

  when: venv_dir is defined

- include: patch.yml
