---

- name: determine Python site-packages path
  shell: "{{ venv_dir }}/bin/python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'"
  register: site_packages

- name: list patch files
  shell: ls {{ python_patch_path }}/*.patch
  register: patch_files

- name: patch Python modules
  patch:
    basedir: "{{ site_packages.stdout }}"
    remote_src: True
    src: "{{ item }}"
    strip: 1
  with_items: "{{ patch_files.stdout_lines }}"
