- block:

    - name: install uwsgi (Arch)
      pacman: name={{ item }} state=latest
      with_items:
        - uwsgi
        - uwsgi-plugin-python
      become: yes

    - name: install uwsgi template
      template:
        src: uwsgi.ini
        dest: /etc/uwsgi/{{ project_name }}.ini
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        mode: 0644

    - name: enable uwsgi (Arch)
      service: name=uwsgi@{{ project_name }}.service enabled=yes state=started
      become: yes

  when: ansible_distribution == "Archlinux"
