---

- name: install virtualenvwrapper
  pip:
    executable: pip3
    extra_args: --system
    name: virtualenvwrapper
  become: yes

- name: select virtualenvwrapper Python version
  lineinfile:
    state: present
    dest: "{{ shellrc.stdout }}"
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - export VIRTUALENVWRAPPER_PYTHON={{ python_exe }}
  when: ansible_distribution == "Ubuntu"

- name: update shell startup
  lineinfile:
    state: present
    dest: "{{ shellrc.stdout }}"
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - export WORKON_HOME=$HOME/.virtualenvs
    - source /usr/local/bin/virtualenvwrapper.sh

- name: get virtualenv path
  shell: . {{ shellrc.stdout }} && echo $WORKON_HOME
  register: virtualenvs_dir

- name: compose venv_dir
  set_fact:
    venv_dir: "{{ virtualenvs_dir.stdout }}/{{ inst_name }}"

- name: create virtualenv
  shell: . {{ shellrc.stdout }} && mkvirtualenv -p {{ python_exe }} {{ inst_name }}
  args:
    creates: "{{ venv_dir }}"
