---

- name: install virtualenvwrapper
  pip:
    executable: "{{ pip_exe }}"
    name: virtualenvwrapper

- name: update shell startup
  lineinfile:
    state: present
    dest: "{{ shellrc.stdout }}"
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - export WORKON_HOME=$HOME/.virtualenvs
    - export PROJECT_HOME={{ project_dir }}
    - source /usr/local/bin/virtualenvwrapper.sh

- name: get virtualenv path
  shell: . {{ shellrc.stdout }} >& /dev/null && echo $WORKON_HOME
  register: venv_dir
  when: venv_dir is undefined

- name: create virtualenv
  shell: . {{ shellrc.stdout }} && mkvirtualenv -p {{ python_exe }} {{ inst_name }}
  args:
    creates: "{{ venv_dir.stdout }}/{{ inst_name }}"

# - name: get pip executable
#   shell: . {{ shellrc.stdout }} >& /dev/null && workon {{ inst_name }} && which pip
#   register: pip_exe
