---

- block:

  - name: add nodejs server key
    apt_key: keyserver=keyserver.ubuntu.com id=68576280

  - name: add nodejs repository
    apt_repository: repo='deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'

  - name: install nodejs (Ubuntu)
    apt: name={{ item }} state=latest
    with_items:
      - nodejs

  - name: softlink nodejs binary (Ubuntu)
    file: src=/usr/bin/nodejs dest=/usr/bin/node owner=root group=root state=link

  become: yes
  when: ansible_distribution == "Ubuntu"

- block:

    - name: install nodejs (MacOSX)
      homebrew: name=node

  when: ansible_distribution == "MacOSX"

- name: create node_modules directory
  file: path={{ venv_dir }}/node_modules state=directory

- name: install nodejs dependencies
  npm: path={{ site_root }}

- name: update virtual environment activation script
  lineinfile:
    state: present
    dest: "{{ venv_dir }}/bin/activate"
    line: "{{ item  }}"
    insertafter: EOF
  with_items:
    - export PATH={{ node_modules_path }}/node_modules/.bin:$PATH
    - export NODE_PATH={{ node_modules_path }}/node_modules:$NODE_PATH
  when: venv_dir is defined and node_modules_path is defined
