---

- name: clone repository
  git:
   recursive: yes
   repo: "{{ repository_url }}"
   dest: "{{ site_root }}"
   update: no
   accept_hostkey: yes
   version: "{{ repository_branch }}"
  when: clone_repository
