---

- block:

    - name: check if docker is installed (MacOSX)
      stat: path=/usr/local/bin/docker
      register: docker_bin

  when: ansible_distribution == "MacOSX"


- block:

    - name: check for downloaded file (MacOSX)
      stat: path=/tmp/DockerToolbox-1.9.0.pkg
      register: docker_file

    - name: download docker (MacOSX)
      get_url: dest=/tmp url=https://github.com/docker/toolbox/releases/download/v1.9.0/DockerToolbox-1.9.0.pkg
      when: docker_file.stat.exists == False

    - name: install docker (MacOSX)
      command: installer -pkg /tmp/DockerToolbox-1.9.0.pkg -tgt /
      become: yes

  when: ansible_distribution == "MacOSX" and docker_bin.stat.exists == False


- block:

    - name: add docker source key
      become: yes
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: add docker repository
      become: yes
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-wily main

    - name: install docker
      become: yes
      apt: name={{ item }} state=latest
      with_items:
        - linux-image-extra-{{ ansible_kernel }}
        - docker-engine

    - name: start docker
      become: yes
      service: name=docker state=started enabled=yes

  when: ansible_distribution == "Ubuntu"


- name: install docker-compose
  become: yes
  pip:
    executable: pip
    name: docker-compose


- name: add user to docker group
  become: yes
  user: name={{ ansible_user_id }} groups=docker append=yes
